services:
  backend:
    build: ./server
    container_name: mern-backend
    network_mode: "host"
    env_file:
      - .env

  frontend:
    build: ./client
    container_name: mern-frontend
    network_mode: "host"
    depends_on:
      - backend
